# Generated by Django 3.1.7 on 2021-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of', models.TextField()),
                ('symbol', models.TextField()),
                ('client', models.TextField()),
                ('défaut', models.TextField()),
                ('a_trier', models.IntegerField()),
                ('bonnes', models.IntegerField()),
                ('mauvaises', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
