# Generated by Django 3.1.1 on 2021-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tri',
            old_name='défaut',
            new_name='defaut',
        ),
    ]
