# Generated by Django 3.1.1 on 2021-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tri', '0002_auto_20210306_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tri',
            name='est_trie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tri',
            name='a_trier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tri',
            name='bonnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tri',
            name='client',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tri',
            name='defaut',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tri',
            name='mauvaises',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tri',
            name='of',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tri',
            name='symbol',
            field=models.TextField(default=''),
        ),
    ]
